/*
* Language Format variable should be {x}Set .
* Where x-> language abbrevation w.r.t https://www.w3schools.com/tags/ref_language_codes.asp
*/
/*------------------LANGUAGE OBJECT VARIABLE----------------------*/
var enSet = {
	saf_overlay_P_5: 'Please click on the download symbol',
	overlay_P_5: 'Click <br> here <br> and install.',
	saf_install: ' and install.',
	loading : 'Loading…',
	centeredtext : 'LOADING... PLEASE WAIT.',
	id_HEADER1 : 'Your system is infected with 3 viruses',
	id_E1STPAR_HEAD : 'Your PC is infected with',
	id_E1STPAR_VIRUS : 'viruses. Our security check found traces of',
	id_E1STPAR_MALWARE : 'malware and&nbsp;',
	id_E1STPAR : 'phishing/spyware. System damage: 28.1% - Immediate removal required!',
	id_2NDPAR1 : 'The immediate removal of the viruses is required to prevent further system damage, loss of Apps, Photos or other files.',
	id_E2NDPAR2_TRACES : 'Traces of',
	id_E2NDPAR2 : 'phishing/spyware were found on your PC with',
	id_E2NDPAR3 : 'Personal and banking information is at risk.',
	id_E3RDPAR : 'To avoid more damage click on \'Scan Now\'immediately. Our deep scan will provide help immediately!',
	id_E32RDPARTIMER_MINUTE: 'minute and &nbsp;',
	id_E32RDPARTIMER : 'seconds remaining before damage is permanent.',
	id_BUTTON: 'Scan Now',
	id_SCANPROG : 'SCAN IN PROGRESS',
	id_DOWNLOADNEEDED : 'DOWNLOAD REQUIRED',
	id_HEAVILYDAMAGED : 'Your PC is heavily damaged! (33.2%)',
	id_DOWNLOADMACKEEPER : 'Please download the',
	id_DOWNLOADMACKEEPER_VIRUS : 'application to remove 3 Viruses from your PC.',
	id_VIRUSINFO : 'VIRUS INFORMATION',
	id_VIRNAME : 'Virus Name:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risk:&nbsp;&nbsp;HIGH',
	id_INFECTEDDATA: 'Infected Files:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'REMOVE VIRUSES NOW',
	id_VIRUSREMOVAL : 'VIRUS REMOVAL',
	id_APPLICATION : 'Application:&nbsp;',
	id_RATING : 'Rating:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Price:&nbsp;&nbsp;Free',
	alertwindow: "IMMEDIATE ACTION REQUIRED\n\nWe have detected a trojan virus (e.tre456_worm_Windows) on your PC.\n\nPress OK to begin the repair process.",
	loadingtext1: "Loading",
	loadingtext2 : "Scanning... Folders",
	loadingtext3 : "Scanning... Documents",
	loadingtext4 : "Scanning... System Files",
	loadingtext5 : "Scanning... Registry",
	loadingtext6 : "Scan Complete",
	virfoundtext1 : "Virus Found: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Searching for removal options..."
};

/*
* French
*/
var frSet = {
	saf_overlay_P_5: 'Veuillez cliquer sur l’icône de téléchargement',
	overlay_P_5: 'Cliquez <br> ici <br> et installez.',
	saf_install: ' et installez.',
	loading : 'Chargement en cours…',
	centeredtext : 'CHARGEMENT EN COURS... VEUILLEZ PATIENTER.',
	id_HEADER1 : 'Votre système d’exploitation a été infecté par 3 virus',
	id_E1STPAR_HEAD : 'Votre PC a été infecté par',
	id_E1STPAR_VIRUS : 'des virus. Notre analyse de sécurité a détecté la trace de',
	id_E1STPAR_MALWARE : 'logiciels malveillants et de&nbsp;',
	id_E1STPAR : 'logiciels d’hameçonnage/logiciels espions. . Votre système d’exploitation est endommagé à : 28,1 % - La suppression immédiate de ces virus est fortement recommandée !',
	id_2NDPAR1 : 'Une suppression immédiate de ces virus est nécessaire pour éviter tout autre dommage à votre système d’exploitation et la perte d’applications, de photos et autres fichiers.',
	id_E2NDPAR2_TRACES : 'La trace de',
	id_E2NDPAR2 : 'logiciels d’hameçonnage/logiciels espions a été détectée sur votre PC avec',
	id_E2NDPAR3 : 'Vos données personnelles et informations bancaires sont menacées.',
	id_E3RDPAR : 'Pour éviter plus de dégâts, cliquez immédiatement sur '+"'Analyser maintenant'"+ '. Notre analyse approfondie vous aidera à résoudre ce problème !',
	id_E32RDPARTIMER_MINUTE: 'minute(s) et ',
	id_E32RDPARTIMER : 'seconde(s) restantes avant que les dégâts causés ne soient permanents.',
	id_BUTTON: 'Analyser maintenant',
	id_SCANPROG : 'ANALYSE EN COURS',
	id_DOWNLOADNEEDED : 'TÉLÉCHARGEMENT REQUIS',
	id_HEAVILYDAMAGED : 'Votre PC a été fortement endommagé ! (33,2 %)',
	id_DOWNLOADMACKEEPER : 'Veuillez télécharger',
	id_DOWNLOADMACKEEPER_VIRUS : 'l\'application pour supprimer les 3 virus qui ont infecté votre PC.',
	id_VIRUSINFO : 'INFORMATIONS SUR LES VIRUS',
	id_VIRNAME : 'Nom des virus :&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risque :&nbsp;&nbsp;ÉLEVÉ',
	id_INFECTEDDATA: 'Fichiers infectés :&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'SUPPRIMER LES VIRUS MAINTENANT',
	id_VIRUSREMOVAL : 'SUPPRESSION DES VIRUS',
	id_APPLICATION : 'Application :&nbsp;',
	id_RATING : 'Évaluation :&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Prix:&nbsp;&nbsp;Gratuit',
	alertwindow : "ACTION IMMÉDIATE REQUISE\n\nNous avons détecté un cheval de Troie (e.tre456_worm_Windows) sur votre PC.\n\nAppuyez sur OK pour commencer le processus de réparation.",
	loadingtext1 : "Chargement en cours",
	loadingtext2 : "Analyse des... Dossiers",
	loadingtext3 : "Analyse des... Documents",
	loadingtext4 : "Analyse des... Fichiers système",
	loadingtext5 : "Analyse du... Registre",
	loadingtext6 : "Analyse terminée",
	virfoundtext1 : "Virus trouvés : Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Recherche de solutions adaptées......",
};

/*
* Arabic
*/
var arSet = {
	saf_overlay_P_5: 'يرجى النقر على رمز التنزيل',
	overlay_P_5: 'انقر <br> هنا <br> وقم بالتثبيت.',
	saf_install: ' وقم بالتثبيت.',
	loading : 'جار التحميل…',
	centeredtext : 'جار التحميل... يرجى الانتظار.',
	id_HEADER1 : 'النظام لديك مصاب بـ 3 فيروسات',
	id_E1STPAR_HEAD : 'نظام ماك لديك مصاب بـ',
	id_E1STPAR_VIRUS : 'فيروسات. نظام التحقق الأمني الخاص بنا وجد آثارا لـ',
	id_E1STPAR_MALWARE : 'برمجيات خبيثة و',
	id_E1STPAR : 'برمجيات تصيد/تجسس. نسبة ضرر النظام: 28.1% - يجب إزالة الفيروسات فورا!',
	id_2NDPAR1 : 'يجب إزالة الفيروسات فورا لمنع أي أضرار أخرى للنظام، أو فقدان للتطبيقات أو الصور أو غيرها من الملفات.',
	id_E2NDPAR2_TRACES : 'آثار لـ',
	id_E2NDPAR2 : 'برمجيات تصيد/تجسس تم العثور عليها في نظام ماك الخاص بك',
	id_E2NDPAR3 : 'المعلومات الشخصية والبنكية معرضة للخطر.',
	id_E3RDPAR : 'لمنع أي أضرار أخرى انقر على '+"'الفحص الآن'"+ 'فورا. وستزودك عملية الفحص العميقة بالمساعدة فورا!',
	id_E32RDPARTIMER_MINUTE: 'دقائق و ',
	id_E32RDPARTIMER : 'ثوان متبقية قبل أن يصبح الضرر دائمًا.',
	id_BUTTON: 'الفحص الآن',
	id_SCANPROG : 'الفحص قيد التقدم',
	id_DOWNLOADNEEDED : 'التنزيل مطلوب',
	id_HEAVILYDAMAGED : 'نظام ماك لديك مصاب بضرر شديد! (33.2%)',
	id_DOWNLOADMACKEEPER : 'يرجى تنزيل تطبيق',
	id_DOWNLOADMACKEEPER_VIRUS : 'لإزالة عدد 3 فيروسات من نظام ماك الخاص بك.',
	id_VIRUSINFO : 'معلومات الفيروس',
	id_VIRNAME : 'اسم الفيروس:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'الخطر:&nbsp;&nbsp;مرتفع',
	id_INFECTEDDATA: 'الملفات المصابة:C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'إزالة الفيروسات الآن',
	id_VIRUSREMOVAL : 'إزالة الفيروس',
	id_APPLICATION : 'التطبيق:&nbsp;',
	id_RATING : 'التقييم:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'السعر:&nbsp;&nbsp;مجانا',
	alertwindow : "مطلوب إجراء فوري\n\nلقد اكتشفنا وجود فيروس من نوع تروجان (e.tre456_worm_Windows) على نظام ماك الخاص بك.\n\nانقر على موافق للبدء بعملية الإصلاح.",
	loadingtext1 : "جار التحميل",
	loadingtext2 : "جار فحص... المجلدات",
	loadingtext3 : "جار فحص... المستندات",
	loadingtext4 : "جار فحص... ملفات النظام",
	loadingtext5 : "جار فحص... ملفات السجل",
	loadingtext6 : "اكتمل الفحص",
	virfoundtext1 : "تم العثور على فيروس: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "جار البحث عن خيارات الإزالة...",
};

/*
* Crotian
*/
var hrSet = {
	saf_overlay_P_5: 'Molimo vas da kliknete na simbol preuzimanja',
	overlay_P_5: 'Kliknite <br> ovdje <br> i instalirajte.',
	saf_install: ' i instalirajte.',
	loading : 'Učitavanje…',
	centeredtext : 'UČITAVANJE... MOLIMO PRIČEKAJTE.',
	id_HEADER1 : 'Vaš sistem je zaražen s 3 virusa',
	id_E1STPAR_HEAD : 'Vaš PC je zaražen s',
	id_E1STPAR_VIRUS : 'virusa. Naša sigurnosna provjera je otkrila tragove',
	id_E1STPAR_MALWARE : 'malwarea i&nbsp;',
	id_E1STPAR : 'phishing/spyware programa. Sistemska šteta: 28.1% - Potrebno trenutno uklanjanje!',
	id_2NDPAR1 : 'Potrebno je odmah ukloniti viruse kako bi se spriječilo daljnje oštećivanje sistema, gubitak aplikacija, fotografija ili drugih datoteka.',
	id_E2NDPAR2_TRACES : 'Tragovi',
	id_E2NDPAR2 : 'phishing/spyware programa su pronađeni na vašem PC s',
	id_E2NDPAR3 : 'Vaši osobni i bankovni podaci su ugroženi.',
	id_E3RDPAR : 'Kako biste izbjegli daljnju štetu odmah kliknite na '+"'Skeniraj sada'"+ '. Naše dubinsko skeniranje će odmah osigurati pomoć vašem sistemu!',
	id_E32RDPARTIMER_MINUTE: 'minuta i ',
	id_E32RDPARTIMER : 'sekunda je preostalo prije šteta ne ostavi trajne posljedice.',
	id_BUTTON: 'Skeniraj sada',
	id_SCANPROG : 'SKENIRANJE U TIJEKU',
	id_DOWNLOADNEEDED : 'POTREBNO PREUZIMANJE',
	id_HEAVILYDAMAGED : 'Vaš PC je teško oštećen! (33.2%)',
	id_DOWNLOADMACKEEPER : 'Molimo preuzmite',
	id_DOWNLOADMACKEEPER_VIRUS : 'aplikaciju kako biste uklonili 3 virusa sa svoga PC.',
	id_VIRUSINFO : 'INFORMACIJE O VIRUSU',
	id_VIRNAME : 'Ime virusa:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Rizik:&nbsp;&nbsp;VISOK',
	id_INFECTEDDATA: 'Zaražene datoteke:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'UKLONI VIRUSE SADA',
	id_VIRUSREMOVAL : 'UKLANJANJE VIRUSA',
	id_APPLICATION : 'Aplikacija:&nbsp;',
	id_RATING : 'Ocjena:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Cijena:&nbsp;&nbsp;Besplatno',
	alertwindow : "POTREBNA TRENUTNA AKCIJA\n\nOtkrili smo trojanskog konja (e.tre456_worm_Windows) na vašem PC.\n\nPritisnite OK kako biste započeli proces oporavka.",
	loadingtext1 : "Učitavanje",
	loadingtext2 : "Skeniranje... mapa",
	loadingtext3 : "Skeniranje... dokumenata",
	loadingtext4 : "Skeniranje... sistemskih datoteka",
	loadingtext5 : "Skeniranje... registra",
	loadingtext6 : "Skeniranje završeno",
	virfoundtext1 : "Pronađen virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Pretraživanje opcija uklanjanja...",
};

/*
* Czech
*/
var csSet = {
	saf_overlay_P_5: 'Klikněte prosím na symbol stažení',
	overlay_P_5: 'Klikněte <br> zde <br> a nainstalujte.',
	saf_install: ' a nainstalujte.',
	loading : 'Načítání…',
	centeredtext : 'NAČÍTÁNÍ... ČEKEJTE PROSÍM.',
	id_HEADER1 : 'Váš systém infikovaly 3 viry',
	id_E1STPAR_HEAD : 'Váš PC je infikován',
	id_E1STPAR_VIRUS : 'viry. Naše bezpečnostní kontrola nalezla stopy',
	id_E1STPAR_MALWARE : 'malware a&nbsp;',
	id_E1STPAR : 'phishing/spyware. Poškození systému: 28,1 % – nutné okamžité odstranění!',
	id_2NDPAR1 : 'Je nutné okamžité odstranění virů, abyste zabránili dalšímu poškození systému, ztrátě aplikací, fotografií a dalších souborů.',
	id_E2NDPAR2_TRACES : 'Stopy',
	id_E2NDPAR2 : 'phishing/spyware byly nalezeny na vašem počítači PC s',
	id_E2NDPAR3 : 'Jsou ohroženy osobní a bankovní informace.',
	id_E3RDPAR : 'Ihned klikněte na '+"'Skenovat nyní'"+ ', abyste zabránili dalším škodám. Naše hloubkové skenování vám ihned pomůže!',
	id_E32RDPARTIMER_MINUTE: 'min a ',
	id_E32RDPARTIMER : 's zbývá, než bude poškození trvalé.',
	id_BUTTON: 'Skenovat nyní',
	id_SCANPROG : 'PROBÍHÁ SKENOVÁNÍ',
	id_DOWNLOADNEEDED : 'VYŽADOVÁNO STAŽENÍ',
	id_HEAVILYDAMAGED : 'Váš PC je výrazně poškozen! (33,2 %)',
	id_DOWNLOADMACKEEPER : 'Stáhněte si prosím',
	id_DOWNLOADMACKEEPER_VIRUS : 'aplikaci k odstranění 3 virů z vašeho počítače PC.',
	id_VIRUSINFO : 'INFORMACE O VIRU',
	id_VIRNAME : 'Náze viru:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Riziko:&nbsp;&nbsp;VYSOKÉ',
	id_INFECTEDDATA: 'Nakažené soubory:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'ODSTRANIT VIRUS NYNÍ',
	id_VIRUSREMOVAL : 'ODSTRANĚNÍ VIRU',
	id_APPLICATION : 'Aplikace:&nbsp;',
	id_RATING : 'Hodnocení:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Cena:&nbsp;&nbsp;Zdarma',
	alertwindow : "NUTNÁ OKAMŽITÁ AKCE\n\nNa vašem počítači PC jsem detekovali trojanový trojan virus (e.tre456_worm_Windows).\n\nStisknutím tlačítka OK zahajte proces opravy.",
	loadingtext1 : "Načítání",
	loadingtext2 : "Skenování... Složky",
	loadingtext3 : "Skenování... Dokumenty",
	loadingtext4 : "Skenování... Systémové soubory",
	loadingtext5 : "Skenování... Registry",
	loadingtext6 : "Skenování dokončeno",
	virfoundtext1 : "Nalezen virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Hledání možností odstranění...",
};

/*
* German
*/
var deSet = {
	saf_overlay_P_5: 'Bitte klicken Sie auf das Download-Symbol',
	overlay_P_5: 'Klicken Sie <br> hier <br> und starten Sie die Installation.',
	saf_install: ' und installieren.',
	loading : 'Lädt…',
	centeredtext : 'LÄDT... BITTE WARTEN.',
	id_HEADER1 : 'Ihr System ist mit 3 Viren infiziert',
	id_E1STPAR_HEAD : 'Ihr PC ist infiziert mit',
	id_E1STPAR_VIRUS : 'Viren. Unsere Sicherheitsprüfung fand Spuren von',
	id_E1STPAR_MALWARE : 'Malware und&nbsp;',
	id_E1STPAR : 'Phishing/Spyware. Systemschaden: 28,1 % - sofortige Entfernung erforderlich!',
	id_2NDPAR1 : 'Die sofortige Entfernung der Viren ist erforderlich, um weitere Systemschäden, den Verlust von Apps, Fotos und weiteren Dateien zu verhindern.',
	id_E2NDPAR2_TRACES : 'Spuren von',
	id_E2NDPAR2 : 'Phishing/Spyware wurden auf Ihrem PC gefunden mit',
	id_E2NDPAR3 : 'Ihre privaten Daten und Ihre Bankdaten sind in Gefahr.',
	id_E3RDPAR : 'Zur Vermeidung weiterer Schäden sofort auf '+"'Jetzt scannen"+ 'klicken. Unser Tiefenscan bietet Ihnen umgehende Hilfe!',
	id_E32RDPARTIMER_MINUTE: 'Minute und ',
	id_E32RDPARTIMER : 'Sekunden verbleiben, bis der Schaden dauerhaft ist.',
	id_BUTTON: 'Jetzt scannen',
	id_SCANPROG : 'SCANNEN LÄUFT',
	id_DOWNLOADNEEDED : 'DOWNLOAD ERFORDERLICH',
	id_HEAVILYDAMAGED : 'Ihr PC ist signifikant beschädigt! (33,2 %)',
	id_DOWNLOADMACKEEPER : 'Bitte laden Sie die',
	id_DOWNLOADMACKEEPER_VIRUS : 'Anwendung herunter, um 3 Viren von Ihrem PC zu entfernen.',
	id_VIRUSINFO : 'VIRUSINFORMATION',
	id_VIRNAME : 'Virusname:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risiko:&nbsp;&nbsp;HOCH',
	id_INFECTEDDATA: 'Infizierte Dateien:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'JETZT VIREN ENTFERNEN',
	id_VIRUSREMOVAL : 'VIRUSENTFERNUNG',
	id_APPLICATION : 'Anwendung:&nbsp;',
	id_RATING : 'Bewertung:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Preis:&nbsp;&nbsp;Gratis',
	alertwindow : "SOFORTIGES HANDELN ERFORDERLICH\n\nWir haben einen Trojaner-Virus detektiert auf Ihrem PC detektiert (e.tre456_worm_Windows).\n\nDrücken Sie OK, um die Reparatur zu beginnen.",
	loadingtext1 : "Lädt…",
	loadingtext2 : "Scannen... Ordner",
	loadingtext3 : "Scannen... Dokumente",
	loadingtext4 : "Scannen... Systemdateien",
	loadingtext5 : "Scannen... Registry",
	loadingtext6 : "Scan abgeschlossen",
	virfoundtext1 : "Virus gefunden: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Suche nach Entfernungsoptionen...",
};

/*
* Hindi
*/
var hiSet = {
	saf_overlay_P_5: 'डाउनलोड चिन्ह पर क्लिक करें कृपया',
	overlay_P_5: '<br>यहां<br> पर क्लिक करें और इंस्टॉल करें',
	saf_install: 'और इंस्टॉल करें।',
	loading: 'लोड हो रहा है ...',
	centeredtext: 'लोड हो रहा है... कृपया इंतजार करें।',
	id_HEADER1: 'आपका सिस्टम 3 वायरसों से संक्रमित है',
	id_E1STPAR_HEAD: 'आपका मैक इससे संक्रमित है',
	id_E1STPAR_VIRUS: 'वायरस। हमारी सुरक्षा जांच में इसका पता चला है',
	id_E1STPAR_MALWARE: 'मैलवेयर और& nbsp;',
	id_E1STPAR: 'फ़िशिंग/ स्पाइवेयर। सिस्टम को क्षति: 28.1% - तत्काल हटाने की आवश्यकता है! ',
	id_2NDPAR1: 'वायरस को तत्काल हटाना आवश्यक है ताकि आगे सिस्टम को क्षति, ऐप्स, फोटो या अन्य फ़ाइलों को नुकसान न हो।',
	id_E2NDPAR2_TRACES: 'के निशान',
	id_E2NDPAR2: 'आपके मैक पर इसके साथ फ़िशिंग/ स्पाइवेयर पाए गए',
	id_E2NDPAR3: 'व्यक्तिगत और बैंकिंग जानकारी जोखिम में है।',
	id_E3RDPAR: 'अधिक नुकसान से बचने के लिए '+'"अब स्कैन करें"'+'पर तुरंत क्लिक करें। हमारा गहन स्कैन तुरंत मदद करेगा!',
	id_E32RDPARTIMER_MINUTE: 'मिनट और',
	id_E32RDPARTIMER: 'सेकंड, पूर्ण क्षति से पहले शेष हैं।',
	id_BUTTON: 'अब स्कैन करें',
	id_SCANPROG: 'स्कैन जारी है',
	id_DOWNLOADNEEDED: 'डाउनलोड आवश्यक है',
	id_HEAVILYDAMAGED: 'आपका मैक बहुत अधिक क्षतिग्रस्त है! (33.2%) ',
	id_DOWNLOADMACKEEPER: 'कृपया डाउनलोड करें',
	id_DOWNLOADMACKEEPER_VIRUS: 'ऍप्लिकेशन को अपने मैक से 3 वायरस हटाने के लिए।',
	id_VIRUSINFO: 'वायरस की सूचना',
	id_VIRNAME: 'वायरस का नाम: &nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'जोख़िम:&nbsp;&nbsp;अधिक',
	id_INFECTEDDATA: 'संक्रमित फाइलें:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW: 'अब वायरस हटाएं',
	id_VIRUSREMOVAL: 'वायरस का निष्कासन',
	id_APPLICATION: 'एप्लीकेशन:&nbsp;',
	id_RATING: 'रेटिंग:&nbsp;&nbsp;9.9/10',
	id_PRICE: 'मूल्य:&nbsp;&nbsp;निःशुल्क',
	alertwindow: "तत्काल कार्यवाही की आवश्यकता \n\n हमें आपके मैक पर एक ट्रोजन वायरस (e.tre456_worm_Windows) मिला है। \n\nमरम्मत प्रक्रिया शुरू करने के लिए 'ठीक है' दबाएं।",
	loadingtext1: "लोड हो रहा है",
	loadingtext2: "स्कैन किये जा रहे हैं... फ़ोल्डर",
	loadingtext3: "स्कैन किये जा रहे हैं... दस्तावेज़",
	loadingtext4: "स्कैन किये जा रहे हैं... सिस्टम फ़ाइलें",
	loadingtext5: "स्कैन की जा रही है... रजिस्ट्री",
	loadingtext6: "स्कैन समाप्त हुआ",
	virfoundtext1: "पाए गए वायरस: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2: "निष्कासन विकल्पों के लिए खोज रहे हैं...",
};

/*
* Hungarian
*/
var huSet = {
	saf_overlay_P_5: 'Kérjük, kattints a letöltés jelre',
	overlay_P_5: 'Kattints <br> ide <br> és telepítsd.',
	saf_install: ' és telepítsd.',
	loading : 'Betöltés…',
	centeredtext : 'BETÖLTÉS... KÉRJÜK, VÁRJ.',
	id_HEADER1 : 'A rendszered 3 vírussal fertőzött',
	id_E1STPAR_HEAD : 'A PC-ed fertőzött',
	id_E1STPAR_VIRUS : 'virusokkal. A biztonsági ellenőrzésünk ezeknek találta nyomait:',
	id_E1STPAR_MALWARE : 'rosszindulatú és&nbsp;',
	id_E1STPAR : 'adathalász-/kémprogramok. A rendszer károsodása: 28,1% - azonnali eltávolítás szükséges!',
	id_2NDPAR1 : 'A további rendszerkárosodásnak, appok, fényképek és más fájlok elvesztésének megelőzéséhez azonnal el kell távolítani a vírusoka.',
	id_E2NDPAR2_TRACES : 'Nyomai lettek',
	id_E2NDPAR2 : 'találva adathalász-/kémprogramoknak a PC-eden',
	id_E2NDPAR3 : 'Veszélynek vannak kitéve a személyes és banki információk.',
	id_E3RDPAR : 'További károk elkerüléséhez kattints azonnal az '+"'Átvizsgálás most'"+ ' feliratra. Az alapos vizsgálatunk azonnal segítséget nyújt!',
	id_E32RDPARTIMER_MINUTE: 'perc és ',
	id_E32RDPARTIMER : 'másodperc van hátra a tartós károsodásig.',
	id_BUTTON: 'Átvizsgálás most',
	id_SCANPROG : 'ÁTVIZSGÁLÁS FOLYAMATBAN',
	id_DOWNLOADNEEDED : 'LETÖLTÉS SZÜKSÉGES',
	id_HEAVILYDAMAGED : 'A PC-ed súlyosan károsodott! (33,2%)',
	id_DOWNLOADMACKEEPER : 'Kérjük, töltsd le a(z)',
	id_DOWNLOADMACKEEPER_VIRUS : 'alkalmazást 3 vírus eltávolításához a PC-edről.',
	id_VIRUSINFO : 'VÍRUSINFORMÁCIÓ',
	id_VIRNAME : 'Vírusnév:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Veszély:&nbsp;&nbsp;MAGAS',
	id_INFECTEDDATA: 'Fertőzött fájlok:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'TÁVOLÍTSD EL A VÍRUSOKAT MOST',
	id_VIRUSREMOVAL : 'VÍRUSELTÁVOLÍTÁS',
	id_APPLICATION : 'Alkalmazás:&nbsp;',
	id_RATING : 'Értékelés:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Ár:&nbsp;&nbsp;Ingyenes',
	alertwindow : "AZONNALI CSELEKVÉS SZÜKSÉGES\n\nTrójai vírust fedeztünk fel (e.tre456_worm_Windows) a PC-eden.\n\nNyomd le az OK-t a javítás elkezdéséhez.",
	loadingtext1 : "Betöltés",
	loadingtext2 : "Átvizsgálás... mappák",
	loadingtext3 : "Átvizsgálás... dokumentumok",
	loadingtext4 : "Átvizsgálás... rendszerfájlok",
	loadingtext5 : "Átvizsgálás... regiszter",
	loadingtext6 : "Az átvizsgálás befejeződött",
	virfoundtext1 : "Talált vírus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Eltávolítási opciók keresése...",
};

/*
* Indonesian with id as prefix
*/
var idSet = {
	saf_overlay_P_5: 'Harap klik pada simbol unduh',
	overlay_P_5: 'Klik <br> di sini <br> dan pasang.',
	saf_install: ' dan pasang.',
	loading: 'Memuat...',
	centeredtext: 'MEMUAT... HARAP TUNGGU.',
	id_HEADER1: 'Sistem Anda terinfeksi 3 virus',
	id_E1STPAR_HEAD: 'PC Anda terinfeksi',
	id_E1STPAR_VIRUS: 'virus. Pemeriksaan keamanan kami menemukan jejak',
	id_E1STPAR_MALWARE: 'perangkat lunak perusak dan&nbsp;',
	id_E1STPAR: 'pancingan/spyware. Kerusakan sistem: 28,1% - Penghapusan segera diperlukan!',
	id_2NDPAR1: 'Penghapusan segera virus diperlukan untuk mencegah kerusakan sistem lebih lanjut, hilangnya Aplikasi, Foto, atau berkas lainnya.',
	id_E2NDPAR2_TRACES: 'Jejak',
	id_E2NDPAR2: 'pancingan/spyware ditemukan di PC Anda dengan',
	id_E2NDPAR3: 'Informasi pribadi dan perbankan Anda beresiko.',
	id_E3RDPAR: 'Untuk menghindari lebih banyak kerusakan klik '+'"Pindai Sekarang"'+' dengan segera. Pemindaian mendalam kami akan segera membantu!',
	id_E32RDPARTIMER_MINUTE: 'menit dan',
	id_E32RDPARTIMER: 'detik tersisa sebelum kerusakan permanen.',
	id_BUTTON: 'Pindai Sekarang',
	id_SCANPROG: 'PEMINDAIAN SEDANG BERLANGSUNG',
	id_DOWNLOADNEEDED: 'PENGUNDUHAN DIBUTUHKAN',
	id_HEAVILYDAMAGED: 'PC Anda rusak parah! (33,2%)',
	id_DOWNLOADMACKEEPER: 'Harap unduh',
	id_DOWNLOADMACKEEPER_VIRUS: 'aplikasi untuk menghapus 3 Virus dari PC Anda',
	id_VIRUSINFO: 'INFORMASI VIRUS',
	id_VIRNAME: 'Nama Virus:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risiko:&nbsp;&nbsp;TINGGI',
	id_INFECTEDDATA: 'Berkas Terinfeksi:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW: 'HAPUS VIRUS SEKARANG',
	id_VIRUSREMOVAL: 'PENGHAPUSAN VIRUS',
	id_APPLIKASI: 'Aplikasi:&nbsp;',
	id_RATING: 'Nilai:&nbsp;&nbsp;9.9/10',
	id_PRICE: 'Harga:&nbsp;&nbsp;Gratis',
	alertwindow : "TINDAKAN SEGERA DIBUTUHKAN\n\nKami telah mendeteksi virus trojan (e.tre456_worm_Windows) di PC Anda.\n\nTekan OK untuk memulai proses perbaikan.",
	loadingtext1 : "Memuat",
	loadingtext2 : "Memindai... Folder",
	loadingtext3 : "Memindai... Dokumen",
	loadingtext4 : "Memindai... Berkas Sistem",
	loadingtext5 : "Memindai... Registri",
	loadingtext6 : "Pemindaian Selesai",
	virfoundtext1 : "Ditemukan Virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Mencari pilihan penghapusan...",
};

/*
* Indonesian with in as prefix
*/
var inSet = {
	saf_overlay_P_5: 'Harap klik pada simbol unduh',
	overlay_P_5: 'Klik <br> di sini <br> dan pasang.',
	saf_install: ' dan pasang.',
	loading: 'Memuat...',
	centeredtext: 'MEMUAT... HARAP TUNGGU.',
	id_HEADER1: 'Sistem Anda terinfeksi 3 virus',
	id_E1STPAR_HEAD: 'PC Anda terinfeksi',
	id_E1STPAR_VIRUS: 'virus. Pemeriksaan keamanan kami menemukan jejak',
	id_E1STPAR_MALWARE: 'perangkat lunak perusak dan&nbsp;',
	id_E1STPAR: 'pancingan/spyware. Kerusakan sistem: 28,1% - Penghapusan segera diperlukan!',
	id_2NDPAR1: 'Penghapusan segera virus diperlukan untuk mencegah kerusakan sistem lebih lanjut, hilangnya Aplikasi, Foto, atau berkas lainnya.',
	id_E2NDPAR2_TRACES: 'Jejak',
	id_E2NDPAR2: 'pancingan/spyware ditemukan di PC Anda dengan',
	id_E2NDPAR3: 'Informasi pribadi dan perbankan Anda beresiko.',
	id_E3RDPAR: 'Untuk menghindari lebih banyak kerusakan klik '+'"Pindai Sekarang"'+' dengan segera. Pemindaian mendalam kami akan segera membantu!',
	id_E32RDPARTIMER_MINUTE: 'menit dan',
	id_E32RDPARTIMER: 'detik tersisa sebelum kerusakan permanen.',
	id_BUTTON: 'Pindai Sekarang',
	id_SCANPROG: 'PEMINDAIAN SEDANG BERLANGSUNG',
	id_DOWNLOADNEEDED: 'PENGUNDUHAN DIBUTUHKAN',
	id_HEAVILYDAMAGED: 'PC Anda rusak parah! (33,2%)',
	id_DOWNLOADMACKEEPER: 'Harap unduh',
	id_DOWNLOADMACKEEPER_VIRUS: 'aplikasi untuk menghapus 3 Virus dari PC Anda',
	id_VIRUSINFO: 'INFORMASI VIRUS',
	id_VIRNAME: 'Nama Virus:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risiko:&nbsp;&nbsp;TINGGI',
	id_INFECTEDDATA: 'Berkas Terinfeksi:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW: 'HAPUS VIRUS SEKARANG',
	id_VIRUSREMOVAL: 'PENGHAPUSAN VIRUS',
	id_APPLIKASI: 'Aplikasi:&nbsp;',
	id_RATING: 'Nilai:&nbsp;&nbsp;9.9/10',
	id_PRICE: 'Harga:&nbsp;&nbsp;Gratis',
	alertwindow : "TINDAKAN SEGERA DIBUTUHKAN\n\nKami telah mendeteksi virus trojan (e.tre456_worm_Windows) di PC Anda.\n\nTekan OK untuk memulai proses perbaikan.",
	loadingtext1 : "Memuat",
	loadingtext2 : "Memindai... Folder",
	loadingtext3 : "Memindai... Dokumen",
	loadingtext4 : "Memindai... Berkas Sistem",
	loadingtext5 : "Memindai... Registri",
	loadingtext6 : "Pemindaian Selesai",
	virfoundtext1 : "Ditemukan Virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Mencari pilihan penghapusan...",
};

/*
* Italian
*/
var itSet = {
	saf_overlay_P_5: 'Clicca sul simbolo del download',
	overlay_P_5: 'Clicca <br> qui <br> e installa.',
	saf_install: ' e installa.',
	loading: 'Caricamento in corso...',
	centeredtext: 'CARICAMENTE IN CORSO... ATTENDI.',
	id_HEADER1 : 'Il tuo sistema è infettato da 3 virus',
	id_E1STPAR_HEAD : 'Il tuo PC è stato infettato da',
	id_E1STPAR_VIRUS : 'virus. Il nostro controllo di sicurezza ha trovato tracce di',
	id_E1STPAR_MALWARE : 'malware e &nbsp;',
	id_E1STPAR : 'phishing/spyware. Danni al sistema: 28,1% - Rimozione immediata necessaria!',
	id_2NDPAR1 : 'La rimozione immediata dei virus è necessaria per prevenire ulteriori danni al sistema, perdita di app, foto o altri file.',
	id_E2NDPAR2_TRACES : 'Tracce di',
	id_E2NDPAR2 : 'phishing/spyware sono stati trovati sul tuo PC con',
	id_E2NDPAR3 : "Le informazioni personali e bancarie sono a rischio.",
	id_E3RDPAR : 'Per evitare ulteriori danni clicca su '+"'Scan Now'" + 'immediatamente. La nostra scansione approfondita fornirà un aiuto immediato!',
	id_E32RDPARTIMER_MINUTE : 'minuto and',
	id_E32RDPARTIMER : 'secondi rimanenti prima che il danno sia permanente.',
	id_BUTTON : "Esegui la scansione ora",
	id_SCANPROG : 'SCANSIONE IN CORSO',
	id_DOWNLOADNEEDED : 'DOWNLOAD NECESSARIO',
	id_HEAVILYDAMAGED : 'Il tuo PC è gravemente danneggiato! (33,2%)',
	id_DOWNLOADMACKEEPER : 'Scarica il',
	id_DOWNLOADMACKEEPER_VIRUS : 'applicazione per rimuovere 3 virus dal tuo PC.',
	id_VIRUSINFO : 'INFORMAZIONI SUL VIRUS',
	id_VIRNAME : 'Nome del virus:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Rischio:&nbsp;&nbsp;HIGH',
	id_INFECTEDDATA: 'File infettiFiles:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW: 'RIMUOVI SUBITO I VIRUS',
	id_VIRUSREMOVAL: 'RIMOZIONE VIRUS',
	id_APPLICATION: 'Applicazione:&nbsp;',
	id_RATING: 'Valutazione::&nbsp;&nbsp;9.9/10',
	id_PRICE: "Prezzo:&nbsp;&nbsp;Free",
	alertwindow : 'È NECESSARIA AZIONE IMMEDIATA\n\nabbiamo rilevato un virus trojan (e.tre456_worm_Windows) sul tuo PC.\n\nPremi OK per iniziare il processo di riparazione.',
	loadingtext1 : 'Caricamento',
	loadingtext2 : 'Scansione... cartelle',
	loadingtext3 : 'Scansione... documenti',
	loadingtext4 : 'Scansione ... File di sistema',
	loadingtext5 : 'Scansione ... Registro',
	loadingtext6 : 'Scansione completata',
	virfoundtext1 : 'Virus trovato: Ransomware 2.0; Trojan.Win32.SendIP.15',
	virfoundtext2 : 'Ricerca opzioni di rimozione...',
};

/*
* Japanese
*/
var jaSet = {
	saf_overlay_P_5: 'ダウンロードシンボルをクリックしてください。',
	overlay_P_5: '<br>ここ<br>をクリックしてインストールします。.',
	saf_install: 'インストールします。',
	loading : '読み込み中…',
	centeredtext : '読み込み中... お待ちください。',
	id_HEADER1 : 'システムは3つのウイルスに感染しています',
	id_E1STPAR_HEAD : 'PCは次のウイルスに感染しています',
	id_E1STPAR_VIRUS : 'ウイルス。セキュリティチェックでは次の痕跡が見つかりました：',
	id_E1STPAR_MALWARE : 'マルウェアと&nbsp;',
	id_E1STPAR : 'フィッシング/スパイウェア。 システムの損傷: 28.1% - いますぐ除去が必要です！',
	id_2NDPAR1 : 'さらなるシステムの損傷、アプリ、写真やその他のファイルの損失を防ぐために、ウイルスを即座に削除する必要があります。',
	id_E2NDPAR2_TRACES : '次の痕跡：',
	id_E2NDPAR2 : 'PCでフィッシング/スパイウェアが次と一緒に見つかりました：',
	id_E2NDPAR3 : '個人情報と銀行情報がリスクにさらされています。',
	id_E3RDPAR : '他のダメージを避けるには、 '+"'今すぐスキャン'"+'をすぐにクリックしてください。ディープスキャンはすぐにお手伝いできます！',
	id_E32RDPARTIMER_MINUTE: '分　',
	id_E32RDPARTIMER : '秒で損傷が恒久的に残ります。',
	id_BUTTON: '今すぐスキャン',
	id_SCANPROG : 'スキャンが進行中',
	id_DOWNLOADNEEDED : 'ダウンロードが必要です',
	id_HEAVILYDAMAGED : 'お使いのPCはとても損傷しています！(33.2%)',
	id_DOWNLOADMACKEEPER : '次をダウンロードしてください：',
	id_DOWNLOADMACKEEPER_VIRUS : 'PCから3つのウイルスを削除するアプリケーション。',
	id_VIRUSINFO : 'ウイルスの情報',
	id_VIRNAME : 'ウイルス名：&nbsp;&nbsp;タップスネーク; CronDNS; Dubfishicv',
	id_VIRRISK: 'リスク:&nbsp;&nbsp;高',
	id_INFECTEDDATA: '感染したファイル:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'ウイルスを今すぐ削除',
	id_VIRUSREMOVAL : 'ウイルスの削除',
	id_APPLICATION : 'アプリケーション:&nbsp;',
	id_RATING : '評価:&nbsp;&nbsp;9.9/10',
	id_PRICE : '価格:&nbsp;&nbsp;無料',
	alertwindow : "すぐに行動してください。\n\nお使いのPCでトロイの木馬ウイルス（e.tre456_worm_Windows）が検出されました。\n\n[OK]を押して修復処理を開始してください。",
	loadingtext1 : "読み込み中",
	loadingtext2 : "スキャン中... フォルダ",
	loadingtext3 : "スキャン中... ドキュメント",
	loadingtext4 : "スキャン中... システムファイル",
	loadingtext5 : "スキャン中... レジストリ",
	loadingtext6 : "スキャン完了",
	virfoundtext1 : "見つかったウイルス: タップスネーク; CronDNS; Dubfishicv",
	virfoundtext2 : "削除のオプションを検索中...",
};

/*
* Polish Set
*/
var plSet = {
	saf_overlay_P_5: 'Kliknij symbol pobierania',
	overlay_P_5: 'Kliknij <br> tutaj <br> i zainstaluj.',
	saf_install: 'i zainstaluj.',
	loading : 'Wczytywanie…',
	centeredtext : 'WCZYTYWANIE... PROSZĘ CZEKAĆ.',
	id_HEADER1 : 'Twój system został zainfekowany przez 3 wirusy',
	id_E1STPAR_HEAD : 'Twój PC jest zainfekowany przez',
	id_E1STPAR_VIRUS : 'wirusy. Nasza kontrola bezpieczeństwa wykazała ślady',
	id_E1STPAR_MALWARE : 'malware’u i&nbsp;',
	id_E1STPAR : 'phishingu/spyware’u. Uszkodzenie systemu: 28,1% - wymagane jest natychmiastowe usunięcie!',
	id_2NDPAR1 : 'Wymagane jest natychmiastowe usunięcie wirusów w celu uniknięcia dalszych uszkodzeń systemu, utraty aplikacji, zdjęć i innych plików.',
	id_E2NDPAR2_TRACES : 'Ślady',
	id_E2NDPAR2 : 'phishingu/spyware’u zostały znalezione na urządzeniu PC.',
	id_E2NDPAR3 : 'Dane prywatne oraz bankowe są zagrożone.',
	id_E3RDPAR : 'Aby uniknąć dalszych uszkodzeń, natychmiast kliknij '+"'Skanuj teraz'"+ '. Nasze szczegółowe skanowanie zapewni niezwłoczną pomoc!',
	id_E32RDPARTIMER_MINUTE: 'minuta i',
	id_E32RDPARTIMER : 'sekund pozostało, zanim uszkodzenia okażą się trwałe.',
	id_BUTTON: 'Skanuj teraz',
	id_SCANPROG : 'SKANOWANIE W TOKU',
	id_DOWNLOADNEEDED : 'POBRANIE WYMAGANE',
	id_HEAVILYDAMAGED : 'Twój PC jest poważnie uszkodzony! (33,2%)',
	id_DOWNLOADMACKEEPER : 'Pobierz',
	id_DOWNLOADMACKEEPER_VIRUS : 'aplikację w celu usunięcia 3 wirusów ze swojego urządzenia PC.',
	id_VIRUSINFO : 'INFORMACJE O WIRUSIE',
	id_VIRNAME : 'Nazwa wirusa:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Zagrożenie:&nbsp;&nbsp;POWAŻNE',
	id_INFECTEDDATA: 'Zainfekowane pliki:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'USUŃ WIRUSY TERAZ',
	id_VIRUSREMOVAL : 'USUWANIE WIRUSA',
	id_APPLICATION : 'Aplikacja:&nbsp;',
	id_RATING : 'Ocena:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Cena:&nbsp;&nbsp;Free',
	alertwindow : "WYMAGANE NATYCHMIASTOWE DZIAŁANIE \n\nWykryliśmy wirusa typu trojan (e.tre456_worm_Windows) na Twoim urządzeniu PC.\n\nNaciśnij OK, aby rozpocząć procedurę naprawczą.",
	loadingtext1 : "Wczytywanie",
	loadingtext2 : "Skanowanie... Foldery",
	loadingtext3 : "Skanowanie... Dokumenty",
	loadingtext4 : "Skanowanie... Pliki systemowe ",
	loadingtext5 : "Skanowanie... Rejestr",
	loadingtext6 : "Skanowanie zakończone",
	virfoundtext1 : "Znaleziono wirusa: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Poszukiwanie możliwości usunięcia...",
};

/*
* Portuguese
*/
var ptSet = {
	saf_overlay_P_5: 'Favor clicar no símbolo de download',
	overlay_P_5: 'Clique <br> aqui <br> e instale.',
	saf_install: ' e instale.',
	loading : 'Carregando…',
	centeredtext : 'CARREGANDO... FAVOR ESPERAR.',
	id_HEADER1 : 'Seu sistema está infectado com 3 vírus',
	id_E1STPAR_HEAD : 'Seu PC está infectado com',
	id_E1STPAR_VIRUS : 'vírus. Nossa verificação de segurança encontrou vestígio de',
	id_E1STPAR_MALWARE : 'malware e&nbsp;',
	id_E1STPAR : 'phishing/spyware. Dano ao sistema: 28,1% - Remoção imediata necessária!',
	id_2NDPAR1 : 'A remoção imediata dos vírus é necessária para prevenir mais danos ao sistema, perda de Apps, Fotos ou outros arquivos.',
	id_E2NDPAR2_TRACES : 'Traços de',
	id_E2NDPAR2 : 'phishing/spyware foram encontrados no seu PC com',
	id_E2NDPAR3 : 'As informações pessoais e bancárias estão em risco.',
	id_E3RDPAR : 'Para evitar mais danos, clique em '+"'Varrer agora'"+ 'imediatamente. Nossa varredura profunda vai fornecer ajuda imediatamente!',
	id_E32RDPARTIMER_MINUTE: 'minuto e ',
	id_E32RDPARTIMER : 'segundos restantes antes do dano se tornar permanente.',
	id_BUTTON: 'Varrer Agora',
	id_SCANPROG : 'VARREDURA EM PROGRESSO',
	id_DOWNLOADNEEDED : 'DOWNLOAD NECESSÁRIO',
	id_HEAVILYDAMAGED : 'Seu PC está fortemente danificado! (33,2%)',
	id_DOWNLOADMACKEEPER : 'Baixe o',
	id_DOWNLOADMACKEEPER_VIRUS : 'aplicativo para remover 3 vírus do seu PC.',
	id_VIRUSINFO : 'INFORMAÇÕES SOBRE O VÍRUS',
	id_VIRNAME : 'Nome do vírus:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risco:&nbsp;&nbsp;ALTO',
	id_INFECTEDDATA: 'Arquivos infectados:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'REMOVER VÍRUS AGORA',
	id_VIRUSREMOVAL : 'REMOÇÃO DE VÍRUS',
	id_APPLICATION : 'Aplicativo:&nbsp;',
	id_RATING : 'Classificação:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Preço:&nbsp;&nbsp;Grátis',
	alertwindow : "AÇÃO IMEDIATA NECESSÁRIA\n\nDetectamos um vírus cavalo-de-troia (e.tre456_worm_Windows) em seu PC.\n\nPressione OK para iniciar o processo de reparação.",
	loadingtext1 : "Carregando",
	loadingtext2 : "Varrendo... Pastas",
	loadingtext3 : "Varrendo... Documentos",
	loadingtext4 : "Varrendo... Arquivos do Sistema",
	loadingtext5 : "Varrendo... Registro",
	loadingtext6 : "Varredura Completa",
	virfoundtext1 : "Vírus Encontrados: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Buscando opções de remoção...",
};

/*
* Romanian
*/
var roSet = {
	saf_overlay_P_5: 'Vă rugăm să faceți clic pe simbolul Descărcare',
	overlay_P_5: 'Faceți clic <br> aici <br> și instalați.',
	saf_install: ' și instalați.',
	loading : 'Se încarcă…',
	centeredtext : 'SE ÎNCARCĂ... VĂ RUGĂM SĂ AȘTEPTAȚI.',
	id_HEADER1 : 'Sistemul dvs. este infectat cu 3 viruși',
	id_E1STPAR_HEAD : 'PC-ul dvs. este infectat cu',
	id_E1STPAR_VIRUS : 'viruși. Verificarea noastră de securitate a găsit urme de',
	id_E1STPAR_MALWARE : 'malware și&nbsp;',
	id_E1STPAR : 'phishing/programe spion. Deteriorarea sistemului: 28,1% - Este necesară eliminarea imediată!',
	id_2NDPAR1 : 'Este necesară eliminarea imediată a virușilor pentru a preveni deteriorarea ulterioară a sistemului, pierderea aplicațiilor, fotografiilor sau altor fișiere.',
	id_E2NDPAR2_TRACES : 'Urme de',
	id_E2NDPAR2 : 'phishing/programe spion au fost găsite pe PC-ul dvs. cu',
	id_E2NDPAR3 : 'Informațiile personale și bancare sunt în pericol.',
	id_E3RDPAR : 'Pentru a preveni deteriorarea ulterioară, faceți clic pe '+"'Scanați acum'"+ 'imediat. Scanarea noastră profundă vă va oferi ajutor imediat!',
	id_E32RDPARTIMER_MINUTE: 'minut și ',
	id_E32RDPARTIMER : 'secunde au rămas până când deteriorarea să rămână permanentă.',
	id_BUTTON: 'Scanați acum',
	id_SCANPROG : 'SCANARE ÎN CURS',
	id_DOWNLOADNEEDED : 'ESTE NECESARĂ DESCĂRCAREA',
	id_HEAVILYDAMAGED : 'PC-ul dvs. este grav afectat! (33,2%)',
	id_DOWNLOADMACKEEPER : 'Vă rugăm să descărcați',
	id_DOWNLOADMACKEEPER_VIRUS : 'aplicația pentru a elimina 3 viruși de pe PC-ul dvs.',
	id_VIRUSINFO : 'INFORMAȚII PRIVIND VIRUSUL',
	id_VIRNAME : 'Denumirea virusului:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risc:&nbsp;&nbsp;ÎNALT',
	id_INFECTEDDATA: 'Fișiere infectate:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'ELIMINAȚI VIRUȘII ACUM',
	id_VIRUSREMOVAL : 'ELIMINARE VIRUS',
	id_APPLICATION : 'Applicație:&nbsp;',
	id_RATING : 'Evaluare:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Preț:&nbsp;&nbsp;Free',
	alertwindow : "ESTE NECESAR SĂ INTERVENIȚI IMEDIAT\n\nAm detectat un virus troian (e.tre456_worm_Windows) pe PC-ul dvs.\n\nApăsați pe OK pentru a începe procesul de reparare.",
	loadingtext1 : "Încărcare",
	loadingtext2 : "Scanare... fișiere",
	loadingtext3 : "Scanare... documente",
	loadingtext4 : "Scanare... fișiere de sistem",
	loadingtext5 : "Scanare... registru",
	loadingtext6 : "Scanarea a fost finalizată",
	virfoundtext1 : "Virus găsit: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Căutarea opțiunilor de eliminare...",
};

/*
* Spanish
*/
var esSet = {
	saf_overlay_P_5: 'Haz clic en el símbolo de descarga',
	overlay_P_5: 'Haz clic <br> aquí <br> e instala.',
	saf_install: ' e instala.',
	loading : 'Cargando…',
	centeredtext : 'CARGANDO... ESPERA.',
	id_HEADER1 : 'Tu sistema está infectado con 3 virus',
	id_E1STPAR_HEAD : 'Tu PC está infectado con',
	id_E1STPAR_VIRUS : 'virus. Nuestra comprobación de seguridad ha encontrado rastros de',
	id_E1STPAR_MALWARE : 'malware y&nbsp;',
	id_E1STPAR : 'phishing/spyware. Daño del sistema: 28.1 % - ¡Se requiere eliminación inmediata!',
	id_2NDPAR1 : 'Se requiere la eliminación inmediata de los virus para prevenir daños adicionales del sistema o la pérdida de aplicaciones, fotos u otros archivos.',
	id_E2NDPAR2_TRACES : 'Rastros de',
	id_E2NDPAR2 : 'phishing/spyware se han encontrado en tu PC con',
	id_E2NDPAR3 : 'La información personal y bancaria está en peligro.',
	id_E3RDPAR : 'Para evitar más daños pulsa '+"'Escanear ahora'"+ 'inmediatamente. ¡Nuestro análisis profundo te ayudará al momento!',
	id_E32RDPARTIMER_MINUTE: 'minuto y ',
	id_E32RDPARTIMER : 'segundos restantes antes de que el daño sea permanente.',
	id_BUTTON: '¡Escanear ahora',
	id_SCANPROG : 'ANÁLISIS EN PROCESO',
	id_DOWNLOADNEEDED : 'DESCARGA OBLIGATORIA',
	id_HEAVILYDAMAGED : '¡Tu PC está gravemente dañado! (33.2 %)',
	id_DOWNLOADMACKEEPER : 'Descarga la',
	id_DOWNLOADMACKEEPER_VIRUS : 'aplicación para eliminar 3 virus de tu PC.',
	id_VIRUSINFO : 'INFORMACIÓN SOBRE VIRUS',
	id_VIRNAME : 'Nombre del virus:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Riesgo:&nbsp;&nbsp;ALTO',
	id_INFECTEDDATA: 'Archivos infectados:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'ELIMINAR VIRUS AHORA',
	id_VIRUSREMOVAL : 'ELIMINACIÓN DE VIRUS',
	id_APPLICATION : 'Aplicación:&nbsp;',
	id_RATING : 'Calificación:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Precio:&nbsp;&nbsp;Gratis',
	alertwindow : "SE REQUIERE ACCIÓN INMEDIATA\n\nHemos detectado un virus troyano (e.tre456_worm_Windows) en tu PC.\n\nPulsa ACEPTAR para comenzar el proceso de reparación.",
	loadingtext1 : "Cargando",
	loadingtext2 : "Escaneando... Carpetas",
	loadingtext3 : "Escaneando... Documentos",
	loadingtext4 : "Escaneando... Archivos del sistema",
	loadingtext5 : "Escaneando... Registro",
	loadingtext6 : "Análisis completo",
	virfoundtext1 : "Virus encontrados: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Buscando opciones de eliminación...",
};

/*
* Tagalog
*/
var tlSet = {
	saf_overlay_P_5: 'Mangyaring mag-click sa download symbol',
	overlay_P_5: 'Mag-click <br> dito <br> at i-install.',
	saf_install: ' at install.',
	loading : 'Naglo-load…',
	centeredtext : '... PAKIHINTAY.',
	id_HEADER1 : 'Nahawaan ang iyong system ng 3 virus',
	id_E1STPAR_HEAD : 'Nahawaan ang PC mo ng',
	id_E1STPAR_VIRUS : 'mga virus. Nakakita ang aming security check ng mga bakas ng',
	id_E1STPAR_MALWARE : 'malware at&nbsp;',
	id_E1STPAR : 'phishing/spyware. Pinsala sa system: 28.1% - Kinakailangang tanggalin kaagad!',
	id_2NDPAR1 : 'Kinakailangang tanggalin kaagad ang mga virus upang maiwasan ang karagdagang pinsala sa system, pagkawala ng mga App, Litrato, o iba pang mga file.',
	id_E2NDPAR2_TRACES : 'May mga bakas ng',
	id_E2NDPAR2 : 'phishing/spyware na nakita sa iyong PC na may',
	id_E2NDPAR3 : 'Nasa panganib ang personal na impormasyon at impormasyon ng pagbabangko.',
	id_E3RDPAR : 'Para maiwasan ang karagdagang pinsala, i-click kaagad ang '+"'I-scan Ngayon'"+ '. Ang aming deep scan ay magbibigay kaagad ng tulong!',
	id_E32RDPARTIMER_MINUTE: '(na) minuto at ',
	id_E32RDPARTIMER : '(na) segundo ang natitira bago maging permanente ang pinsala.',
	id_BUTTON: 'I-scan Ngayon',
	id_SCANPROG : 'ISINASAGAWA ANG PAG-SCAN',
	id_DOWNLOADNEEDED : 'KAILANGANG I-DOWNLOAD',
	id_HEAVILYDAMAGED : 'Malubhang napinsala ang iyong PC! (33.2%)',
	id_DOWNLOADMACKEEPER : 'Paki-download ang',
	id_DOWNLOADMACKEEPER_VIRUS : 'application para tanggalin ang 3 Virus sa iyong PC.',
	id_VIRUSINFO : 'IMPORMASYON NG VIRUS',
	id_VIRNAME : 'Pangalan ng Virus&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Panganib:&nbsp;&nbsp;MATAAS',
	id_INFECTEDDATA: 'Mga Nahawaang File:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'TANGGALIN ANG MGA VIRUS NGAYON',
	id_VIRUSREMOVAL : 'PAGTANGGAL NG VIRUS',
	id_APPLICATION : 'Application:&nbsp;',
	id_RATING : 'Rating:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Presyo:&nbsp;&nbsp;Libre',
	alertwindow : "KAILANGAN NG AGARANG AKSYON\n\nNakakita kami ng trojan virus (e.tre456_worm_Windows) sa iyong PC.\n\nPindutin ang OK para simulan ang proseso ng pagkukumpuni.",
	loadingtext1 : "Naglo-load",
	loadingtext2 : "Ini-scan ang... Mga Folder",
	loadingtext3 : "Ini-scan ang... Mga Dokumento",
	loadingtext4 : "Ini-scan ang... Mga System File",
	loadingtext5 : "Ini-scan ang... Registry",
	loadingtext6 : "Tapos na ang Pag-scan",
	virfoundtext1 : "Nakitang Virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Naghahanap ng mga opsyon sa pagtatanggal...",
};

/*
* Vietnamese
*/
var viSet = {
	saf_overlay_P_5: 'Vui lòng nhấn vào biểu tượng tải về',
	overlay_P_5: 'Nhấn <br> vào đây <br> và cài đặt.',
	saf_install: ' và cài đặt.',
	loading : 'Đang tải…',
	centeredtext : 'ĐANG TẢI... VUI LÒNG CHỜ.',
	id_HEADER1 : 'Hệ thống đã bị nhiễm 3 virus',
	id_E1STPAR_HEAD : 'Máy PC đã bị nhiễm',
	id_E1STPAR_VIRUS : 'virus. Hệ thống bảo mật của chúng tôi kiểm tra các dấu vết được tìm thấy của',
	id_E1STPAR_MALWARE : 'phần mềm độc hại và&nbsp;',
	id_E1STPAR : 'phần mềm lừa đảo/gián điệp. Tổn hại hệ thống: 28,1% - Yêu cầu diệt ngay lập tức!',
	id_2NDPAR1 : 'Yêu cầu diệt virus ngay lập tức để ngăn gây thêm tổn hại cho hệ thống, làm mất Ứng dụng, Hình ảnh và các tập tin khác.',
	id_E2NDPAR2_TRACES : 'Phát hiện các dấu vết của',
	id_E2NDPAR2 : 'phần mềm lừa đảo/gián điệp trên máy PC của bạn với',
	id_E2NDPAR3 : 'thông tin Cá nhân và ngân hàng đang gặp nguy hiểm.',
	id_E3RDPAR : 'Để tránh gây thêm thiệt hại, hãy nhấn '+"'Quét Ngay'"+ 'lập tức. Trình quét sâu của chúng tôi sẽ cung cấp hỗ trợ tức thì!',
	id_E32RDPARTIMER_MINUTE: 'phút và ',
	id_E32RDPARTIMER : 'giây còn lại trước khi thiệt hại gây ra là vĩnh viễn.',
	id_BUTTON: 'Quét Ngay',
	id_SCANPROG : 'ĐANG TRONG QUÁ TRÌNH QUÉT',
	id_DOWNLOADNEEDED : 'YÊU CẦU TẢI VỀ',
	id_HEAVILYDAMAGED : 'Máy PC của bạn bị thiệt hại nặng! (33,2%)',
	id_DOWNLOADMACKEEPER : 'Vui lòng tải về ứng dụng',
	id_DOWNLOADMACKEEPER_VIRUS : 'để diệt 3 Virus trên máy PC của bạn.',
	id_VIRUSINFO : 'THÔNG TIN VIRUS',
	id_VIRNAME : 'Tên Virus:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Rủi ro:&nbsp;&nbsp;CAO',
	id_INFECTEDDATA: 'Tập tin bị Nhiễm:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'DIỆT VIRUS NGAY',
	id_VIRUSREMOVAL : 'DIỆT VIRUS',
	id_APPLICATION : 'Ứng dụng:&nbsp;',
	id_RATING : 'Đánh giá:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Giá:&nbsp;&nbsp;Miễn phí',
	alertwindow : "YÊU CẦU HÀNH ĐỘNG NGAY\n\nChúng tôi đã phát hiện một virus trojan (e.tre456_worm_Windows) trên máy PC của bạn.\n\nNhấn OK để bắt đầu quá trình sửa chữa.",
	loadingtext1 : "Đang tải",
	loadingtext2 : "Đang quét... Thư mục",
	loadingtext3 : "Đang quét... Tài liệu",
	loadingtext4 : "Đang quét... Tập tin Hệ Thống",
	loadingtext5 : "Đang quét... Registry",
	loadingtext6 : "Quét Hoàn Tất",
	virfoundtext1 : "Tìm thấy Virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Đang tìm kiếm tùy chọn diệt virus...",
};

/*
* Greek
*/
var elSet = {
	saf_overlay_P_5: 'Κάντε κλικ στο σύμβολο λήψης',
	overlay_P_5: 'Κάντε κλικ <br> εδώ <br> και εγκαταστήστε.',
	saf_install: ' και εγκαταστήστε.',
	loading : 'Γίνεται φόρτωση…',
	centeredtext : 'ΓΙΝΕΤΑΙ ΦΟΡΤΩΣΗ... ΠΑΡΑΚΑΛΩ ΠΕΡΙΜΕΝΕΤΕ.',
	id_HEADER1 : 'Το σύστημά σας είναι μολυσμένο με 3 ιούς',
	id_E1STPAR_HEAD : 'Το PC σας είναι μολυσμένο με',
	id_E1STPAR_VIRUS : 'ιούς. Ο έλεγχος ασφαλείας μας βρήκε ίχνη από',
	id_E1STPAR_MALWARE : 'κακόβουλο λογισμικό και&nbsp;',
	id_E1STPAR : 'phishing/spyware. Βλάβη συστήματος: 28.1% - Απαιτείται άμεση αφαίρεση!',
	id_2NDPAR1 : 'Απαιτείται άμεση αφαίρεση των ιών για να αποτρέψετε περαιτέρω ζημιές στο σύστημα, απώλεια Εφαρμογών, Φωτογραφιών ή άλλων αρχείων.',
	id_E2NDPAR2_TRACES : 'Βρέθηκαν ίχνη από',
	id_E2NDPAR2 : 'phishing/spyware στο PC σας με',
	id_E2NDPAR3 : 'Οι προσωπικές και τραπεζικές πληροφορίες διατρέχουν κίνδυνο.',
	id_E3RDPAR : 'Για να αποφύγετε περισσότερες βλάβες κάντε κλικ στο '+"'Σάρωση Τώρα'"+ 'αμέσως. Η σάρωση σε βάθος θα σας βοηθήσει άμεσα!',
	id_E32RDPARTIMER_MINUTE: 'λεπτό και ',
	id_E32RDPARTIMER : 'δευτερόλεπτα απομένουν προτού η βλάβη να είναι μόνιμη.',
	id_BUTTON: 'Σάρωση Τώρα',
	id_SCANPROG : 'ΣΑΡΩΣΗ ΣΕ ΕΞΕΛΙΞΗ',
	id_DOWNLOADNEEDED : 'ΑΠΑΙΤΕΙΤΑΙ ΛΗΨΗ',
	id_HEAVILYDAMAGED : 'Το PC σας έχει υποστεί σοβαρή ζημιά! (33.2%)',
	id_DOWNLOADMACKEEPER : 'Παρακαλούμε κάντε λήψη της',
	id_DOWNLOADMACKEEPER_VIRUS : 'εφαρμογής για να αφαιρέσετε 3 Ιούς από το PC σας.',
	id_VIRUSINFO : 'ΠΛΗΡΟΦΟΡΙΕΣ ΙΟΥ',
	id_VIRNAME : 'Όνομα Ιού:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Κίνδυνος:&nbsp;&nbsp;ΥΨΗΛΟΣ',
	id_INFECTEDDATA: 'Μολυσμένα Αρχεία:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'ΑΦΑΙΡΕΣΗ ΙΩΝ ΤΩΡΑ',
	id_VIRUSREMOVAL : 'ΑΦΑΙΡΕΣΗ ΙΟΥ',
	id_APPLICATION : 'Εφαρμογή:&nbsp;',
	id_RATING : 'Βαθμολογία:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Τιμή:&nbsp;&nbsp;Free',
	alertwindow : "ΑΠΑΙΤΕΙΤΑΙ ΑΜΕΣΗ ΔΡΑΣΗ\n\nΈχουμε εντοπίσει έναν ιό trojan (e.tre456_worm_Windows) στο PC σας.\n\nΠατήστε OK για να ξεκινήσει η διαδικασία επισκευής.",
	loadingtext1 : "Γίνεται φόρτωση",
	loadingtext2 : "Γίνεται σάρωση... Φάκελοι",
	loadingtext3 : "Γίνεται σάρωση... Εγγραφα",
	loadingtext4 : "Γίνεται σάρωση... Αρχεία συστήματος",
	loadingtext5 : "Γίνεται σάρωση... Αρχείο",
	loadingtext6 : "Η σάρωση ολοκλώθηηρκε",
	virfoundtext1 : "Ιός που Βρέθηκε: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Αναζήτηση επιλογών αφαίρεσης...",
};

/*
* Kurdish
*/
var kuSet = {
	saf_overlay_P_5: 'تکایە کرتە بکە لەسەر هێمای داگرتن',
	overlay_P_5: 'کرتە بکە <br> لێرە <br> و دامەزرێنە.',
	saf_install: ' و دامەزرێنە.',
	loading : 'باردەکات…',
	centeredtext : 'باردەکات... تکایە چاوەڕێبە.',
	id_HEADER1 : 'سیستمەکەت 3 ڤایرۆسی تووشبووە',
	id_E1STPAR_HEAD : 'کۆمپیوتەری PC ی تۆ',
	id_E1STPAR_VIRUS : 'ڤایرۆسی تووشبووە. پشکنینی ئاسایشمان ئاسەواری',
	id_E1STPAR_MALWARE : 'زیانەواڵە و&nbsp;',
	id_E1STPAR : 'فیشینگ/بەرنامەی سیخوڕی دۆزیەوە. زیانی سیستم: 28.1% - لابردنی دەسبەجێ پێویستە!',
	id_2NDPAR1 : 'لابردنی دەسبەجێی ڤایرۆسەکان پێویستە بۆ ڕێگریکردن لە زیانگەیشتن بە سیستم، لەدەستدانی کاربەرنامەکان، وێنەکان یان فایلەکانی تر.',
	id_E2NDPAR2_TRACES : 'ئاسەواری',
	id_E2NDPAR2 : 'فیشینگ/بەرنامەی سیخوڕ لەسەر کۆمپیوتەری PC ی تۆ دۆزرایەوە لەگەڵ',
	id_E2NDPAR3 : 'هەبوونی مەترسی لەسەر زانیاری کەسیی و بانکیی.',
	id_E3RDPAR : 'بۆ بەدوور بوون لە زیانی زیاتر کرتە بکە لەسەر '+"'ئێستا سکان بکە'"+ 'دەسبەجێ. سکانکردنی قووڵی ئێمە یارمەتی دەسبەجێ دەستەبەر دەکات!',
	id_E32RDPARTIMER_MINUTE: 'خولەک و ',
	id_E32RDPARTIMER : 'چرکە ماوە پێش ئەوەی زیانەکە ببێت بە هەمیشەیی.',
	id_BUTTON: 'ئێستا سکان بکە',
	id_SCANPROG : 'سکانکردن لەبەرەوپێشچووندایە',
	id_DOWNLOADNEEDED : 'داگرتن پێویستە',
	id_HEAVILYDAMAGED : 'کۆمپیوتەری PC ی تۆ بەتووندی زیانی پێگەیشتووە! (33.2%)',
	id_DOWNLOADMACKEEPER : 'تکایە کاربەرنامەی',
	id_DOWNLOADMACKEEPER_VIRUS : 'دابگرە بۆ لابردنی 3 ڤایرۆس لە کۆمپیوتەری PC ی تۆ.',
	id_VIRUSINFO : 'زانیاری ڤایرۆس',
	id_VIRNAME : 'ناوی ڤایرۆس:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'مەترسی:&nbsp;&nbsp;بەرز',
	id_INFECTEDDATA: 'فایلە تووشبووەکان:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'ئێستا ڤایرۆسەکان لاببە',
	id_VIRUSREMOVAL : 'لابردنی ڤایرۆس',
	id_APPLICATION : 'کاربەرنامە:&nbsp;',
	id_RATING : 'نمرەپێدان:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'نرخ:&nbsp;&nbsp;خۆڕایی',
	alertwindow : "کرداری دەسبەجێ پێویستە\n\nڤایرۆسێکی ترۆجانمان دۆزیەوە (e.tre456_worm_Windows) لەسەر کۆمپیوتەری PC ی تۆ.\n\nباشە دابگرە بۆ دەستپێکردن بە پرۆسەی چاکردنەوە.",
	loadingtext1 : "باردەکات",
	loadingtext2 : "سکان دەکات... فۆڵدەرەکان",
	loadingtext3 : "سکان دەکات... بەڵگەنامەکان",
	loadingtext4 : "سکان دەکات... فایلەکانی سیستم",
	loadingtext5 : "سکان دەکات... تۆمار",
	loadingtext6 : "سکان تەواو",
	virfoundtext1 : "ڤایرۆس دۆزرایەوە: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "بۆ بژاردەکانی لابردن دەگەڕێت...",
};

/*
* Mandarin
*/
var zhSet = {
	saf_overlay_P_5: '請點擊下載符號',
	overlay_P_5: '點擊<br>這裡<br>並安裝。',
	saf_install: '並安裝。',
	loading : '載入中…',
	centeredtext : '載入中... 請稍等。',
	id_HEADER1 : '您的系統中感染了3個病毒',
	id_E1STPAR_HEAD : '您的PC感染了',
	id_E1STPAR_VIRUS : '病毒。我們的安全檢查發現了',
	id_E1STPAR_MALWARE : '惡意軟體和&nbsp;',
	id_E1STPAR : '釣魚/間諜軟體。系統損毀：28.1% - 需要立即移除！',
	id_2NDPAR1 : '需要立即移除病毒，避免系統進一步損毀，應用、相片或其他檔案丟失。',
	id_E2NDPAR2_TRACES : '發現',
	id_E2NDPAR2 : '您的PC 上有釣魚/間諜軟體，',
	id_E2NDPAR3 : '您的個人資料和銀行資料有危險。',
	id_E3RDPAR : '為避免更多損毀，請即刻點選'+"「立即掃描」"+ '。我們的深度掃描將立即為您提供幫助！',
	id_E32RDPARTIMER_MINUTE: '分',
	id_E32RDPARTIMER : '秒剩餘，此後將永久損毀。',
	id_BUTTON: '立即掃描',
	id_SCANPROG : '正在掃描',
	id_DOWNLOADNEEDED : '需要下載',
	id_HEAVILYDAMAGED : '您的PC已嚴重損毀！ (33.2%)',
	id_DOWNLOADMACKEEPER : '請下載',
	id_DOWNLOADMACKEEPER_VIRUS : '應用程式以移除您PC上的3個病毒。',
	id_VIRUSINFO : '病毒資訊',
	id_VIRNAME : '病毒名稱：&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: '風險等級：&nbsp;&nbsp;高',
	id_INFECTEDDATA: '感染的檔案：&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : '立即移除病毒',
	id_VIRUSREMOVAL : '病毒移除',
	id_APPLICATION : '應用：&nbsp;',
	id_RATING : '評分：&nbsp;&nbsp;9.9/10',
	id_PRICE : '價格：&nbsp;&nbsp;免費',
	alertwindow : "需要立即行動\n\n我們在您的PC上偵測到一個木馬病毒 (e.tre456_worm_Windows)。\n\n點選「好」開始修復程序。",
	loadingtext1 : "載入中",
	loadingtext2 : "正在掃描...檔案",
	loadingtext3 : "正在掃描...文件",
	loadingtext4 : "正在掃描...系統檔",
	loadingtext5 : "正在掃描...登錄檔",
	loadingtext6 : "掃描完成",
	virfoundtext1 : "發現的病毒：Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "正在搜尋移除選項...",
};

/*
* Thai
*/
var thSet = {
	saf_overlay_P_5: 'โปรดคลิกสัญลักษณ์ดาวน์โหลด',
	overlay_P_5: 'คลิก<br>ที่นี่<br>และติดตั้ง',
	saf_install: ' และติดตั้ง',
	loading : 'กำลังโหลด...',
	centeredtext : 'กำลังโหลด... โปรดรอ',
	id_HEADER1 : 'ระบบของคุณติดเชื้อไวรัส 3 รายการ',
	id_E1STPAR_HEAD : 'PC ของคุณติดเชื้อ',
	id_E1STPAR_VIRUS : 'ไวรัส การตรวจสอบความปลอดภัยของเราพบร่องรอยของ',
	id_E1STPAR_MALWARE : 'มัลแวร์และ',
	id_E1STPAR : 'การฟิชชิ่ง/สปายแวร์ ความเสียหายของระบบ: 28.1% - ต้องกำจัดทันที!',
	id_2NDPAR1 : 'ต้องกำจัดไวรัสทันทีเพื่อป้องกันความเสียหายของระบบเพิ่มเติม การสูญเสียแอป รูปภาพหรือไฟล์อื่น ๆ',
	id_E2NDPAR2_TRACES : 'พบร่องรอยของ',
	id_E2NDPAR2 : 'ฟิชชิ่ง/สปายแวร์บน PC ของคุณด้วย',
	id_E2NDPAR3 : 'ข้อมูลส่วนตัวและข้อมูลธนาคารกำลังตกอยู่ในความเสี่ยง',
	id_E3RDPAR : 'เพื่อเลี่ยงความเสียหายเพิ่มเติม คลิก '+"'สแกนตอนนี้'"+ ' ทันที การสแกนเชิงลึกของเราจะมอบการช่วยเหลือให้ในทันที!',
	id_E32RDPARTIMER_MINUTE: 'นาทีและ ',
	id_E32RDPARTIMER : 'วินาทีเหลืออยู่ก่อนความเสียหายจะคงอยู่ถาวร',
	id_BUTTON: 'สแกนตอนนี้',
	id_SCANPROG : 'กำลังอยู่ระหว่างการสแกน',
	id_DOWNLOADNEEDED : 'ต้องดาวน์โหลด',
	id_HEAVILYDAMAGED : 'PC ของคุณเสียหายอย่างรุนแรง! (33.2%)',
	id_DOWNLOADMACKEEPER : 'โปรดดาวน์โหลด',
	id_DOWNLOADMACKEEPER_VIRUS : 'แอปพลิเคชันเพื่อกำจัดไวรัส 3 รายการออกจาก PC ของคุณ',
	id_VIRUSINFO : 'ข้อมูลไวรัส',
	id_VIRNAME : 'ชื่อไวรัส:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'ความเสี่ยง:&nbsp;&nbsp;สูง',
	id_INFECTEDDATA: 'ไฟล์ที่ติดเชื้อ:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'กำจัดไวรัสตอนนี้',
	id_VIRUSREMOVAL : 'การกำจัดไวรัส',
	id_APPLICATION : 'แอปพลิเคชัน:&nbsp;',
	id_RATING : 'คะแนน:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'ราคา:&nbsp;&nbsp;ฟรี',
	alertwindow : "ต้องการการดำเนินการทันที\n\nเราตรวจพบไวรัสโทรจัน (e.tre456_worm_Windows) บน PC ของคุณ\n\nกด ตกลง เพื่อเริ่มกระบวนการซ่อมแซม",
	loadingtext1 : "กำลังโหลด",
	loadingtext2 : "กำลังสแกน... โฟลเดอร์",
	loadingtext3 : "กำลังสแกน... เอกสาร",
	loadingtext4 : "กำลังสแกน... ไฟล์ระบบ",
	loadingtext5 : "กำลังสแกน... รีจิสทรี",
	loadingtext6 : "การสแกนเสร็จสิ้น",
	virfoundtext1 : "ไวรัสที่พบ: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "กำลังค้นหาตัวเลือกในการกำจัด...",
};

/*
* Turkish
*/
var trSet = {
	saf_overlay_P_5: 'Lütfen indir sembolüne tıkla',
	overlay_P_5: '<br> Buraya <br> tıkla ve yükle.',
	saf_install: ' ve yükle.',
	loading : 'Yükleniyor…',
	centeredtext : 'YÜKLENİYOR... LÜTFEN BEKLE.',
	id_HEADER1 : 'Sistemine 3 virüs bulaşmış',
	id_E1STPAR_HEAD : 'PC\'ine',
	id_E1STPAR_VIRUS : 'virüs bulaşmış. Güvenlik kontrolümüzde şu izler bulundu:',
	id_E1STPAR_MALWARE : 'kötü amaçlı yazılım ve&nbsp;',
	id_E1STPAR : 'kimlik hırsızlığı/casus yazılım. Sistem hasarı: %28,1 - Hemen kaldırılması gereklidir!',
	id_2NDPAR1 : 'Daha fazla sistem hasarının, Uygulamaların, Fotoğrafların ve diğer dosyaların kaybolmasını önlemek için virüslerin hemen kaldırılması gereklidir.',
	id_E2NDPAR2_TRACES : 'PC\'inde',
	id_E2NDPAR2 : 'kimlik hırsızlığı/casus yazılım bulundu ve',
	id_E2NDPAR3 : 'Kişisel bilgiler ve bankacılık bilgileri tehlikede.',
	id_E3RDPAR : 'Daha fazla hasarı önlemek için hemen '+"'Şimdi Tara'"+ 'düğmesine tıkla. Derin taramamız hemen yardım sunacaktır!',
	id_E32RDPARTIMER_MINUTE: 'dakika ve ',
	id_E32RDPARTIMER : 'saniye içinde hasar kalıcı olacaktır.',
	id_BUTTON: 'Şimdi Tara',
	id_SCANPROG : 'TARAMA SÜRÜYOR',
	id_DOWNLOADNEEDED : 'İNDİRME GEREKLİDİR',
	id_HEAVILYDAMAGED : 'PC\'in ağır hasar görmüş! (%33,2)',
	id_DOWNLOADMACKEEPER : 'Lütfen',
	id_DOWNLOADMACKEEPER_VIRUS : 'uygulamayı indirerek PC\'inden 3 Virüsü kaldır.',
	id_VIRUSINFO : 'VIRÜS BİLGİLERİ',
	id_VIRNAME : 'Virus Name:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risk:&nbsp;&nbsp;YÜKSEK',
	id_INFECTEDDATA: 'BULAŞMIŞ Files:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'VİRÜSLERİ ŞİMDİ KALDIR',
	id_VIRUSREMOVAL : 'VIRÜS KALDIRMA İŞLEMİ',
	id_APPLICATION : 'Uygulama:&nbsp;',
	id_RATING : 'Puan:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Fiyat:&nbsp;&nbsp;Free',
	alertwindow : "HEMEN EYLEM GEREKLİDİR\n\nPC'inde bir truva atı (e.tre456_worm_Windows) tespit ettik.\n\nOnarım sürecini başlatmak için Tamam düğmesine bas.",
	loadingtext1 : "Yükleniyor",
	loadingtext2 : "Taranıyor... Klasörler",
	loadingtext3 : "Taranıyor... Belgeler",
	loadingtext4 : "Taranıyor... Sistem Dosyaları",
	loadingtext5 : "Taranıyor... Kayıt Defteri",
	loadingtext6 : "Tarama Tamamlandı",
	virfoundtext1 : "Virüs Bulundu: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Kaldırma seçenekleri aranıyor...",
};

/*
* Korean
*/
var koSet = {
	saf_overlay_P_5: '다운로드 심볼을 클릭하십시오',
	overlay_P_5: '<br> 여기 <br>를 클릭하여 설치하십시오.',
	saf_install: ' 그리고 설치하십시오.',
	loading : '로딩 중…',
	centeredtext : '로딩 중... 잠시 기다려 주세요.',
	id_HEADER1 : '시스템이 3종의 바이러스에 감염되었습니다',
	id_E1STPAR_HEAD : '당신의 PC이 바이러스에',
	id_E1STPAR_VIRUS : '감염되었습니다. 저희 시큐리티체크는 ',
	id_E1STPAR_MALWARE : '악성코드와&nbsp;',
	id_E1STPAR : '피싱/스파이웨어를 발견했습니다. 시스템손상: 28.1% - 즉시 제거해야 합니다!',
	id_2NDPAR1 : '바이러스를 즉시 제거해야 시스템 손상과 앱, 사진을 비롯한 기타 파일의 더 큰 손상을 막을 수 있습니다.',
	id_E2NDPAR2_TRACES : '바이러스의 흔적:',
	id_E2NDPAR2 : '피싱/스파이웨어가 당신의 PC에서 발견되었으며,',
	id_E2NDPAR3 : '개인 정보와 은행 정보가 위험합니다.',
	id_E3RDPAR : '더 큰 피해를 막으려면, 즉시 '+"'지금 스캔하기'"+'를 클릭하십시오. 저희 딥 스캔이 즉시 도와드리겠습니다!',
	id_E32RDPARTIMER_MINUTE: '분 ',
	id_E32RDPARTIMER : '초 후에는 피해가 영구화됩니다.',
	id_BUTTON: '지금 스캔',
	id_SCANPROG : '스캔 중',
	id_DOWNLOADNEEDED : '필수 요소 다운로드',
	id_HEAVILYDAMAGED : '당신의 PC이 심각하게 손상되었습니다! (33.2%)',
	id_DOWNLOADMACKEEPER : '다음 앱을 다운로드하십시오:',
	id_DOWNLOADMACKEEPER_VIRUS : 'PC에서 3 종의 바이러스를 제거하는 애플리케이션.',
	id_VIRUSINFO : '바이러스 정보',
	id_VIRNAME : '바이러스 이름:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: '위험도:&nbsp;&nbsp;높음',
	id_INFECTEDDATA: '감염된 파일:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : '지금 바이러스 제거',
	id_VIRUSREMOVAL : '바이러스 제거',
	id_APPLICATION : '애플리케이션:&nbsp;',
	id_RATING : '평가:&nbsp;&nbsp;9.9/10',
	id_PRICE : '가격:&nbsp;&nbsp;무료',
	alertwindow : "즉각적인 행동 필요합니다\n\n당신의 PC에서 트로이 목마 바이러스(e.tre456_worm_Windows)를 탐지했습니다.\n\n리페어 과정을 시작하려면 OK를 누르십시오.",
	loadingtext1 : "로딩 중",
	loadingtext2 : "폴더... 스캔 중",
	loadingtext3 : "문서... 스캔 중",
	loadingtext4 : "시스템 파일... 스캔 중",
	loadingtext5 : "레지스트리... 스캔 중",
	loadingtext6 : "스캔 완료",
	virfoundtext1 : "바이러스 발견: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "바이러스 제거 옵션 탐색 중...",
};

/*
* Dutch
*/
var nlSet = {
	saf_overlay_P_5: 'Klik op het downloadsymbool',
	overlay_P_5: 'Click <br> hier <br> en installeer.',
	saf_install: ' en installeer.',
	loading : 'Aan het laden…',
	centeredtext : 'AAN HET LADEN... EVEN GEDULD.',
	id_HEADER1 : 'Uw systeem is besmet met 3 virussen',
	id_E1STPAR_HEAD : 'Uw PC is besmet met',
	id_E1STPAR_VIRUS : 'virussen. Onze veiligheidscontrole heeft sporen gevonden van',
	id_E1STPAR_MALWARE : 'malware en&nbsp;',
	id_E1STPAR : 'phishing/spyware. Systeemschade: 28,1% - Onmiddellijke verwijdering vereist!',
	id_2NDPAR1 : 'De onmiddellijke verwijdering van de virussen is vereist om verdere systeemschade en het verlies van apps, foto’s en andere bestanden te voorkomen.',
	id_E2NDPAR2_TRACES : 'Sporen van',
	id_E2NDPAR2 : 'phishing/spyware zijn op uw PC aangetroffen met',
	id_E2NDPAR3 : 'Uw persoonlijke en bankinformatie zijn in gevaar.',
	id_E3RDPAR : 'Om verdere schade te voorkomen, klik onmiddelijk op '+"'Nu scannen'"+'Onze diepe scan zal onmiddellijk hulp bieden!',
	id_E32RDPARTIMER_MINUTE: 'minuut en ',
	id_E32RDPARTIMER : 'seconden voordat de schade permanent wordt.',
	id_BUTTON: 'Nu scannen',
	id_SCANPROG : 'AAN HET SCANNEN',
	id_DOWNLOADNEEDED : 'DOWNLOAD VEREIST',
	id_HEAVILYDAMAGED : 'Uw PC heeft aanzienlijke schade! (33,2%)',
	id_DOWNLOADMACKEEPER : 'Download de',
	id_DOWNLOADMACKEEPER_VIRUS : 'applicatie om 3 virussen van uw PC te verwijderen.',
	id_VIRUSINFO : 'VIRUSINFORMATIE',
	id_VIRNAME : 'Virusnaam:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risico:&nbsp;&nbsp;HOOG',
	id_INFECTEDDATA: 'Besmette bestanden:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'VIRUSSEN NU VERWIJDEREN',
	id_VIRUSREMOVAL : 'VIRUSVERWIJDERING',
	id_APPLICATION : 'Applicatie:&nbsp;',
	id_RATING : 'Beoordeling:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Prijs:&nbsp;&nbsp;Gratis',
	alertwindow : "ONMIDDELLIJKE ACTIE VEREIST \n\nWe hebben een Trojaans virus (e.tre456_worm_Windows) op uw PC gedetecteerd.\n\nDruk op OK om het reparatieproces te starten.",
	loadingtext1 : "Aan het laden",
	loadingtext2 : "Scannen... Mappen",
	loadingtext3 : "Scannen... Documenten",
	loadingtext4 : "Scannen... Systeembestanden ",
	loadingtext5 : "Scannen... Register",
	loadingtext6 : "Scan compleet",
	virfoundtext1 : "Gevonden virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Aan het zoeken naar verwijderingsopties...",
};

/*
* Danish
*/
var daSet = {
	saf_overlay_P_5: 'Klik venligst på download-symbolet',
	overlay_P_5: 'Klik <br> her <br> og installer.',
	saf_install: ' og installer.',
	loading : 'Indlæser…',
	centeredtext : 'INDLÆSER... VENT VENLIGST.',
	id_HEADER1 : 'Dit system er inficeret med 3 virusser',
	id_E1STPAR_HEAD : 'Din PC er inficeret med',
	id_E1STPAR_VIRUS : 'virusser. Vores sikkerhedstjek har fundet spor af',
	id_E1STPAR_MALWARE : 'malware og&nbsp;',
	id_E1STPAR : 'phishing/spyware. Systemskade: 28.1% - Omgående fjernelse påkrævet!',
	id_2NDPAR1 : 'Den omgående fjernelse af virusserne er nødvendig for at forebygge yderligere skade på systemet og tab af apper, fotos eller andre filer.',
	id_E2NDPAR2_TRACES : 'Spor af',
	id_E2NDPAR2 : 'phishing/spyware blev fundet på din PC med',
	id_E2NDPAR3 : 'Private og bankoplysninger er i fare.',
	id_E3RDPAR : 'For at undgå flere skader, klik på '+"'Scan nu'"+ 'straks. Vores grundige scanning hjælper straks!',
	id_E32RDPARTIMER_MINUTE: 'minut og ',
	id_E32RDPARTIMER : 'sekunder tilbage før skaden er permanent.',
	id_BUTTON: 'Scan nu',
	id_SCANPROG : 'SCANNING I GANG',
	id_DOWNLOADNEEDED : 'DOWNLOAD NØDVENDIGT',
	id_HEAVILYDAMAGED : 'Din PC er alvorligt skadet! (33.2%)',
	id_DOWNLOADMACKEEPER : 'Download venligst',
	id_DOWNLOADMACKEEPER_VIRUS : 'applikationen for at fjerne 3 virusser fra din PC.',
	id_VIRUSINFO : 'VIRUS-INFORMATION',
	id_VIRNAME : 'Virus-navn:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risk:&nbsp;&nbsp;HØJ',
	id_INFECTEDDATA: 'Inficerede filer:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'FJERN VIRUSSER NU',
	id_VIRUSREMOVAL : 'FJERNELSE AF VIRUSSER',
	id_APPLICATION : 'Applikation:&nbsp;',
	id_RATING : 'Bedømmelse:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Pris:&nbsp;&nbsp;Gratis',
	alertwindow : "OMGÅENDE HANDLING NØDVENDIGVi har opdaget en trojanervirus (e.tre456_worm_Windows) på din PC. Tryk OK for at begynde reparationsprocessen.",
	loadingtext1 : "Indlæser",
	loadingtext2 : "Scanner... Mapper",
	loadingtext3 : "Scanner... Dokumenter",
	loadingtext4 : "Scanner... Systemfiler",
	loadingtext5 : "Scanner... Registeret",
	loadingtext6 : "Scan Færdigt",
	virfoundtext1 : "Virus fundet: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Leder efter muligheder for fjernelse...",
};

/*PC
* Finnish
*/
var fiSet = {
	saf_overlay_P_5: 'Napsauta latauskuvaketta',
	overlay_P_5: 'Napsauta <br> tästä <br> asentaaksesi.',
	saf_install: ' asentaaksesi.',
	loading : 'Ladataan…',
	centeredtext : 'LADATAAN... ODOTA HETKI.',
	id_HEADER1 : 'Järjestelmästäsi löytyi 3 virustartuntaa',
	id_E1STPAR_HEAD : 'PCiltasi löytyi',
	id_E1STPAR_VIRUS : 'virusta. Turvatarkastuksemme löysi jälkiä',
	id_E1STPAR_MALWARE : 'haittaohjelmasta ja&nbsp;',
	id_E1STPAR : 'tietojenkalastelusta/vakoiluohjelmasta. Järjestelmän vauriotila: 28,1 % - Suorita korjaustoimenpiteet välittömästi!',
	id_2NDPAR1 : 'Sinun tulee poistaa virukset välittömästi estääksesi lisävaurioiden aiheutumisen järjestelmälle, sekä sovellusten, valokuvien ja muiden tiedostojen menettämisen.',
	id_E2NDPAR2_TRACES : 'Jälkiä',
	id_E2NDPAR2 : 'tietojenkalastelusta/vakoiluohjelmasta, joiden johdosta',
	id_E2NDPAR3 : 'Henkilö- ja pankkitietosi ovat vaarassa.',
	id_E3RDPAR : 'Estä lisävahingot napsauttamalla '+"'Skannaa nyt'"+ 'välittömästi. Syväskannauksemme avustaa sinua välittömästi!',
	id_E32RDPARTIMER_MINUTE: 'minuuttia ja ',
	id_E32RDPARTIMER : 'sekuntia jäljellä ennen kuin vahingot jäävät pysyviksi.',
	id_BUTTON: 'Skannaa nyt',
	id_SCANPROG : 'SKANNAUS KÄYNNISSÄ',
	id_DOWNLOADNEEDED : 'LATAUS VAADITAAN',
	id_HEAVILYDAMAGED : 'PCisi on merkittävästi vaurioitunut! (33,2 %)',
	id_DOWNLOADMACKEEPER : 'Lataa',
	id_DOWNLOADMACKEEPER_VIRUS : '-sovellus poistaaksesi 3 virusta PCiltasi.',
	id_VIRUSINFO : 'VIRUKSEN TIEDOT',
	id_VIRNAME : 'Viruksen nimi:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Riski:&nbsp;&nbsp;HIGH',
	id_INFECTEDDATA: 'Saastuneet tiedostot:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'POISTA VIRUKSET NYT',
	id_VIRUSREMOVAL : 'VIRUSTEN POISTO',
	id_APPLICATION : 'Sovellus:&nbsp;',
	id_RATING : 'Arviot:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Hinta:&nbsp;&nbsp;Ilmainen',
	alertwindow : "VÄLITTÖMIÄ TOIMENPITEITÄ EDELLYTETÄÄN PCillasi on havaittu e.tre456_worm_Windows -virus. Paina OK aloittaaksesi korjausprosessi.",
	loadingtext1 : "Ladataan",
	loadingtext2 : "Skannataan... Kansioita",
	loadingtext3 : "Skannataan... Dokumentteja",
	loadingtext4 : "Skannataan... Järjestelmätiedostoja",
	loadingtext5 : "Skannataan... Rekisteriä",
	loadingtext6 : "Skannaus valmis",
	virfoundtext1 : "Löydetty virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Etsitään tietoa poistotavoista...",
};

/*
* Norwegian
*/
var noSet = {
	saf_overlay_P_5: 'Trykk på nedlastingssymbolet',
	overlay_P_5: 'Trykk <br> her <br> for å installere.',
	saf_install: ' og installer.',
	loading : 'Laster …',
	centeredtext : 'LASTER … VENT.',
	id_HEADER1 : 'Systemet ditt er infisert med 3 virus',
	id_E1STPAR_HEAD : 'Din PC er infisert med',
	id_E1STPAR_VIRUS : 'virus. Sikkerhetssjekken vår fant spor av',
	id_E1STPAR_MALWARE : 'skadelig programvare og&nbsp;',
	id_E1STPAR : 'nettfisking/spionprogramvare. Systemskade: 28,1 %. Dette må fjernes umiddelbart!',
	id_2NDPAR1 : 'Virusene må fjernes umiddelbart for å hindre mer skade på systemet, samt tap av programmer, bilder eller andre filer.',
	id_E2NDPAR2_TRACES : 'Spor av',
	id_E2NDPAR2 : 'nettfisking/spionprogramvare ble funnet på din PC',
	id_E2NDPAR3 : 'noe som betyr at personlige opplysninger og bankinfo er i faresonen.',
	id_E3RDPAR : 'Trykk på '+'«Skann nå»'+ 'med en gang for å unngå mer skade. Den grundige skanningsprosessen vår hjelper deg umiddelbart!',
	id_E32RDPARTIMER_MINUTE: 'minutt og ',
	id_E32RDPARTIMER : 'sekunder gjenstår før skaden er uopprettelig.',
	id_BUTTON: 'Skann nå',
	id_SCANPROG : 'SKANNINGEN PÅGÅR',
	id_DOWNLOADNEEDED : 'MÅ LASTES NED',
	id_HEAVILYDAMAGED : 'Din PC er alvorlig skadet! (33,2%)',
	id_DOWNLOADMACKEEPER : 'Last ned',
	id_DOWNLOADMACKEEPER_VIRUS : 'programmet for å fjerne 3 virus fra din PC.',
	id_VIRUSINFO : 'VIRUSINFO',
	id_VIRNAME : 'Virusnavn:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risiko:&nbsp;&nbsp;HØY',
	id_INFECTEDDATA: 'Infiserte filer:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'FJERN VIRUS NÅ',
	id_VIRUSREMOVAL : 'VIRUSFJERNING',
	id_APPLICATION : 'Program:&nbsp;',
	id_RATING : 'Rangering:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Pris:&nbsp;&nbsp;Free',
	alertwindow : "DU MÅ GJØRE NOE UMIDDELBART Vi har funnet et trojansk virus (e.tre456_worm_Windows) på din PC.Trykk på «OK» for å starte repareringen.",
	loadingtext1 : "Laster",
	loadingtext2 : "Skanner … Mapper",
	loadingtext3 : "Skanner … Dokumenter",
	loadingtext4 : "Skanner … systemfiler",
	loadingtext5 : "Skanner … registre",
	loadingtext6 : "Skanningen er fullført",
	virfoundtext1 : "Vi fant følgende virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Søker etter alternativer for fjerning",
};

/*
* Swedish
*/
var svSet = {
	saf_overlay_P_5: 'Vänligen klicka på nedladdningssymbolen',
	overlay_P_5: 'Klicka <br> här <br> och installera.',
	saf_install: ' och installera.',
	loading : 'Laddar…',
	centeredtext : 'LADDAR... VÄNLIGEN VÄNTA.',
	id_HEADER1 : 'Ditt system är infekterat med 3 virus',
	id_E1STPAR_HEAD : 'DIn PC är infekterat med',
	id_E1STPAR_VIRUS : 'virus. Vår säkerhetskontroll fann spår av',
	id_E1STPAR_MALWARE : 'skadlig kod och&nbsp;',
	id_E1STPAR : 'nätfiske/spionprogram. Systemskada: 28,1 % - omedelbart avlägsnande krävs!',
	id_2NDPAR1 : 'Omedelbart avlägsnande av virus krävs för att förhindra ytterligare systemskada, förlust av appar, foton eller andra filer.',
	id_E2NDPAR2_TRACES : 'Spår av',
	id_E2NDPAR2 : 'nätfiske/spionprogram hittades på din PC med',
	id_E2NDPAR3 : 'Person- och bankuppgifter är utsatta.',
	id_E3RDPAR : 'För att undvika mer skada, klicka på '+"'Skanna nu'"+ 'omedelbart. Vår djup-skanning hjälper dig omedelbart!',
	id_E32RDPARTIMER_MINUTE: 'minut och ',
	id_E32RDPARTIMER : 'sekunder kvarstår innan skadan är permanent.',
	id_BUTTON: 'Skanna nu',
	id_SCANPROG : 'SKANNING PÅGÅR',
	id_DOWNLOADNEEDED : 'NEDLADDNING KRÄVS',
	id_HEAVILYDAMAGED : 'Din PC är mycket skadad! (33,2 %)',
	id_DOWNLOADMACKEEPER : 'Vänligen ladda ned',
	id_DOWNLOADMACKEEPER_VIRUS : 'applikationen för att avlägsna 3 virus från din PC.',
	id_VIRUSINFO : 'VIRUSINFORMATION',
	id_VIRNAME : 'Virusnamn:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risk:&nbsp;&nbsp;HÖG',
	id_INFECTEDDATA: 'Infekterade filer:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'AVLÄGSNA VIRUS NU',
	id_VIRUSREMOVAL : 'VIRUSAVLÄGSNANDE',
	id_APPLICATION : 'Applikation:&nbsp;',
	id_RATING : 'Betyg:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Pris:&nbsp;&nbsp;gratis',
	alertwindow : "OMEDELBAR ÅTGÄRD KRÄVSVi har upptäckt ett trojanskt virus (e.tre456_worm_Windows) på din PC.Tryck OK för att påbörja reparationsprocessen.",
	loadingtext1 : "Laddar",
	loadingtext2 : "Skannar... mappar",
	loadingtext3 : "Skannar... dokument",
	loadingtext4 : "Skannar... systemfiler",
	loadingtext5 : "Skannar... register",
	loadingtext6 : "Skanning slutförd",
	virfoundtext1 : "Virus funna: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Söker efter avlägsnandealternativ...",
};
